### ISSUE TITLE
CMake cannot find lua 

### ISSUE THREAD

**Issue by coldfix** [xs-embedded-llc/l2dbus#6]
Hey,

When running the cmake configuration phase, I get the following error:

```
...
-- Searching for Lua 5.1
CMake Error at /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Lua: Found unsuitable version "", but required is at least
  "5.1" (found /usr/lib64/liblua.so;/usr/lib64/libm.so)
Call Stack (most recent call first):
  /usr/share/cmake-3.2/Modules/FindPackageHandleStandardArgs.cmake:372 (_FPHSA_FAILURE_MESSAGE)
  CMakeModules/FindLua.cmake:121 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:70 (find_package)
```

I'm running archlinux and have both lua51 and lua (52) installed.

I figured out, that the problem can be fixed by the following patch in `CMakeLists.txt`:

```diff
-find_package(Lua ${L2DBUS_LUA_VERSION} REQUIRED)
+find_package(Lua REQUIRED)
```

I was wondering if you have any experience with this issue and know a better fix?

Best regards,
Thomas

**Comment by gschmottlach** [comment]
Unfortunately, I don't have any experience with that particular issue although I haven't tried building it on archlinux. I suspect the Lua packages are named/versioned differently from what's assumed. It appears your patch just eliminates the Lua version check altogether. 

The CMake module that "finds" Lua can be found in CMakeModules/FindLua.cmake within the L2DBUS project. I suspect you could modify that to "find" the correct version under archlinux. How are the Lua libraries named in that distro? I suspect it differs from the general versioning approach used on Ubuntu and other distros. Typically, I build this code under Yocto using Bitbake and friends for a custom Linux distro targeted at embedded Linux devices.

Looks like you have a work-around regardless. For any future patch, I think I'd be more interested in addressing potential issues in the FindLua.cmake module where this is probably failing. Without an archlinux platform to play with it would be tough for me to come with an alternative solution to help you. If you devise another patch for FindLua.cmake, I'd consider including it if it doesn't break things for other distros.

Thanks for you continued interest and contributions. Perhaps it will help other archlinux users use the library.

Glenn

**Comment by coldfix** [comment]
Hey,

Thanks for your reply.

> It appears your patch just eliminates the Lua version check altogether. 

Yes, I did that because the error message seemed to indicate, that my cmake couldn't determine the lua version at all.

> The CMake module that "finds" Lua can be found in CMakeModules/FindLua.cmake within the L2DBUS project. I suspect you could modify that to "find" the correct version under archlinux.

I had a short look at FindLua.cmake/FindPackage.cmake yesterday already, but for my unaccustomed eyes cmake is rather cryptic, so I thought I'll ask you first if you know anything. When I get some spare time, I will try again and send you (or the cmake guys) a patch - if I find a reasonable fix.

> How are the Lua libraries named in that distro?

```lua /usr/lib/liblua.so
lua /usr/lib/liblua.so.5.2
lua /usr/lib/liblua.so.5.2.4
lua /usr/lib/pkgconfig/lua.pc
lua51 /usr/lib/liblua.so.5.1
lua51 /usr/lib/liblua.so.5.1.5
lua51 /usr/lib/liblua5.1.so
lua51 /usr/lib/liblua5.1.so.5.1
lua51 /usr/lib/liblua5.1.so.5.1.5
lua51 /usr/lib/pkgconfig/lua5.1.pc
```

Thanks again,
Thomas

**Comment by tysenmoore-xse** [comment]
When you run `cmake .` does it complain about not finding the Lua version?

**Comment by coldfix** [comment]
Yes, same warning with using `cmake` directly as with `build_host.sh`. In fact, I noticed, because someone flagged the [l2dbus-git package on the AUR](https://aur.archlinux.org/packages/l2dbus-git/) out of date, where the build is configured as follows:

```
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$pkgdir/usr"
```

**Comment by tysenmoore-xse** [comment]
What version of cmake are you using in ArchLinux?

I pulled an ArchLinux VM and it is using cmake version 3.2.1.  With this new version we no longer need /l2dbus/CModules/FindLua.cmake.  We can use the new and improved version provided by cmake.  So please try to remove /l2dbus/CModules/FindLua.cmake and rebuild--this worked for me.  If this works we will need to see how we can support older versions of cmake.  For example, Ubuntu 14.04 uses 2.8.12.2 which does not provide FindLua.cmake.

**Comment by coldfix** [comment]
Oh great, deleting CMakeModules/FindLua.cmake fixes the problem. I didn't realize, you had a custom FindLua.cmake module inside the repository and just looked at the system-provided version. Please tell me, how you will handle this, so I can update the AUR package: if the FindLua.cmake stays for now, I will simply remove it before the configuration phase.

**Comment by tysenmoore-xse** [comment]
I just pushed up some improvements to the cmake files.  I've now added a copy of the newer FindLua.cmake for older cmake versions that don't provide the files.  So you should be OK without any special processing, as will the older Ubuntu cmake.  Let me know if you have other questions/problems.

**Comment by coldfix** [comment]
Great, it works! Thanks.
