### ISSUE TITLE
Porting of l2dbus onto openwrt-x86

### ISSUE THREAD

**Issue by sachin9900** [xs-embedded-llc/l2dbus#7]
Hello,
I am trying to port l2dbus and their dependencies onto openwrt-x86. For that i am using i486-openwrt-linux-gcc toolchain. 
i created cmake.toolchain with following lines:
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_C_COMPILER i486-openwrt-linux-gcc)
SET(CMAKE_CXX_COMPILER i486-openwrt-linux-g++)

I exported following environment variables:
export OPENWRT_SOURCE=/home/sachin/OPENWRT
export STAGING_DIR=$OPENWRT_SOURCE/staging_dir
export TOOLCHAIN_DIR=$STAGING_DIR/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2
export PATH=$TOOLCHAIN_DIR/bin:$PATH
export PREFIX_PATH=$STAGING_DIR/host

I installed the all dependencies in this PREFIX_PATH.
Then i did run the ./build_target -DCMAKE_INSTALL_PREFIX=$PREFIX_PATH
after this we got folllowing log:
************log*************************
-- The C compiler identification is unknown
-- Check for working C compiler: i486-openwrt-linux-gcc
CMake Error: your C compiler: "i486-openwrt-linux-gcc" was not found.   Please set CMAKE_C_COMPILER to a valid compiler path or name.
CMake Error: Internal CMake error, TryCompile configure of cmake failed
-- Check for working C compiler: i486-openwrt-linux-gcc -- broken
CMake Error at /usr/share/cmake-2.8/Modules/CMakeTestCCompiler.cmake:61 (message):
  The C compiler "i486-openwrt-linux-gcc" is not able to compile a simple
  test program.

  It fails with the following output:

   

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:2 (PROJECT)

CMake Error: your C compiler: "i486-openwrt-linux-gcc" was not found.   Please set CMAKE_C_COMPILER to a valid compiler path or name.
-- Configuring incomplete, errors occurred!
See also "/home/sachin/IOTAP/BUILD/cdbus-master/armv7l-Release/CMakeFiles/CMakeOutput.log".
See also "/home/sachin/IOTAP/BUILD/cdbus-master/armv7l-Release/CMakeFiles/CMakeError.log".
sachin:cdbus-master$ . ../config.conf 
sachin:cdbus-master$ ./build_target.sh 
Target environment may not be set up properly!

Build target not found - assuming default (armv7l)
==> Running cmake for armv7l-Release . . .

-- The C compiler identification is GNU 4.8.3
-- Check for working C compiler: /home/sachin/IOTAP/barrier_breaker/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-gcc
-- Check for working C compiler: /home/sachin/IOTAP/barrier_breaker/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done

-- cdbus building as Release
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'dbus-1>=1.4.0'
--   found dbus-1, version 1.6.18
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- checking for module 'ev'
--   package 'ev' not found
-- Will link with libev found here: /usr/local/lib/libev.so
-- LIBEV_PKG_INCLUDE_DIRS: /usr/local/include
-- LIBEV_PKG_LIBRARY_DIRS: /usr/local/lib
-- checking for module 'glib-2.0>=2.0.0'
--   found glib-2.0, version 2.38.2

-- Compile cdbus using: make
-- Install cdbus using: make install
-- Uninstall cdbus using: make uninstall
-- Compile public API documentation using: make pub-docs
-- Install public API documentation using: make install-docs
-- Uninstall public API documentation using: make uninstall-docs
-- Create cdbus source distribution using: make dist-cdbus
-- (be sure to set the correct CMAKE_INSTALL_PREFIX before)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/sachin/IOTAP/BUILD/cdbus-master/armv7l-Release
Scanning dependencies of target CDBUS_MAIN_LOOP_EV_STATIC
[  2%] Building C object CMakeFiles/CDBUS_MAIN_LOOP_EV_STATIC.dir/src/main-loop/main-loop-ev.c.o
Linking C static library lib/libcdbus-ev.a
[  2%] Built target CDBUS_MAIN_LOOP_EV_STATIC
Scanning dependencies of target CDBUS_STATIC
[  4%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/condvar-posix.c.o
[  6%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/timeout-priv.c.o
[  8%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/atomic-ops.c.o
[ 10%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/object-priv.c.o
[ 12%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/interface-priv.c.o
[ 14%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/trace.c.o
[ 16%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/watch-priv.c.o
[ 18%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dbus-watch-ctrl.c.o
[ 20%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/introspect-priv.c.o
[ 22%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dbus-timeout-ctrl.c.o
[ 25%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dispatcher-priv.c.o
[ 27%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/string-pointer-map.c.o
[ 29%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/alloc.c.o
[ 31%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/pipe-posix.c.o
[ 33%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/init.c.o
[ 35%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/connection-priv.c.o
[ 37%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/mutex-posix.c.o
[ 39%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/match.c.o
[ 41%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/pointer-pointer-map.c.o
[ 43%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/stringbuffer.c.o
[ 45%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/semaphore-posix.c.o
[ 47%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/object-registry.c.o
Linking C static library lib/libcdbus.a
[ 47%] Built target CDBUS_STATIC
Scanning dependencies of target CDBUS_SHARED
[ 50%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/condvar-posix.c.o
[ 52%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/timeout-priv.c.o
[ 54%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/atomic-ops.c.o
[ 56%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/object-priv.c.o
[ 58%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/interface-priv.c.o
[ 60%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/trace.c.o
[ 62%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/watch-priv.c.o
[ 64%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dbus-watch-ctrl.c.o
[ 66%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/introspect-priv.c.o
[ 68%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dbus-timeout-ctrl.c.o
[ 70%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dispatcher-priv.c.o
[ 72%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/string-pointer-map.c.o
[ 75%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/alloc.c.o
[ 77%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/pipe-posix.c.o
[ 79%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/init.c.o
[ 81%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/connection-priv.c.o
[ 83%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/mutex-posix.c.o
[ 85%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/match.c.o
[ 87%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/pointer-pointer-map.c.o
[ 89%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/stringbuffer.c.o
[ 91%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/semaphore-posix.c.o
[ 93%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/object-registry.c.o
Linking C shared library lib/libcdbus.so
/home/sachin/IOTAP/barrier_breaker/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/lib/gcc/i486-openwrt-linux-uclibc/4.8.3/../../../../i486-openwrt-linux-uclibc/bin/ld: cannot find -ldbus-1
collect2: error: ld returned 1 exit status
make[2]: *** [lib/libcdbus.so.] Error 1
make[1]: *** [CMakeFiles/CDBUS_SHARED.dir/all] Error 2
make: *** [all] Error 2

**************end of log***************

When i did export of PKG_CONFIG_PATH that got compiled and did build libraries correctly.
export PKG_CONFIG_PATH=$PREFIX_PATH/lib/pkgconfig
but the log i seen is: 
**********log2*******
-- The C compiler identification is GNU 4.8.3
-- Check for working C compiler: /home/sachin/IOTAP/barrier_breaker/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-gcc
-- Check for working C compiler: /home/sachin/IOTAP/barrier_breaker/staging_dir/toolchain-i386_i486_gcc-4.8-linaro_uClibc-0.9.33.2/bin/i486-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done

-- cdbus building as Release
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for module 'dbus-1>=1.4.0'
--   found dbus-1, version 1.8.6
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.6") 
-- checking for module 'ev'
--   package 'ev' not found
-- Will link with libev found here: /usr/local/lib/libev.so
-- LIBEV_PKG_INCLUDE_DIRS: /usr/local/include
-- LIBEV_PKG_LIBRARY_DIRS: /usr/local/lib
-- checking for module 'glib-2.0>=2.0.0'
--   found glib-2.0, version 2.41.1

-- Compile cdbus using: make
-- Install cdbus using: make install
-- Uninstall cdbus using: make uninstall
-- Compile public API documentation using: make pub-docs
-- Install public API documentation using: make install-docs
-- Uninstall public API documentation using: make uninstall-docs
-- Create cdbus source distribution using: make dist-cdbus
-- (be sure to set the correct CMAKE_INSTALL_PREFIX before)

-- Configuring done
-- Generating done
-- Build files have been written to: /home/sachin/IOTAP/BUILD/cdbus-master/armv7l-Release
Scanning dependencies of target CDBUS_MAIN_LOOP_EV_STATIC
[  2%] Building C object CMakeFiles/CDBUS_MAIN_LOOP_EV_STATIC.dir/src/main-loop/main-loop-ev.c.o
Linking C static library lib/libcdbus-ev.a
[  2%] Built target CDBUS_MAIN_LOOP_EV_STATIC
Scanning dependencies of target CDBUS_STATIC
[  4%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/condvar-posix.c.o
[  6%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/timeout-priv.c.o
[  8%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/atomic-ops.c.o
[ 10%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/object-priv.c.o
[ 12%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/interface-priv.c.o
[ 14%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/trace.c.o
[ 16%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/watch-priv.c.o
[ 18%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dbus-watch-ctrl.c.o
[ 20%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/introspect-priv.c.o
[ 22%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dbus-timeout-ctrl.c.o
[ 25%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/dispatcher-priv.c.o
[ 27%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/string-pointer-map.c.o
[ 29%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/alloc.c.o
[ 31%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/pipe-posix.c.o
[ 33%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/init.c.o
[ 35%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/connection-priv.c.o
[ 37%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/mutex-posix.c.o
[ 39%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/match.c.o
[ 41%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/pointer-pointer-map.c.o
[ 43%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/stringbuffer.c.o
[ 45%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/semaphore-posix.c.o
[ 47%] Building C object CMakeFiles/CDBUS_STATIC.dir/src/object-registry.c.o
Linking C static library lib/libcdbus.a
[ 47%] Built target CDBUS_STATIC
Scanning dependencies of target CDBUS_SHARED
[ 50%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/condvar-posix.c.o
[ 52%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/timeout-priv.c.o
[ 54%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/atomic-ops.c.o
[ 56%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/object-priv.c.o
[ 58%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/interface-priv.c.o
[ 60%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/trace.c.o
[ 62%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/watch-priv.c.o
[ 64%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dbus-watch-ctrl.c.o
[ 66%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/introspect-priv.c.o
[ 68%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dbus-timeout-ctrl.c.o
[ 70%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/dispatcher-priv.c.o
[ 72%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/string-pointer-map.c.o
[ 75%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/alloc.c.o
[ 77%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/pipe-posix.c.o
[ 79%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/init.c.o
[ 81%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/connection-priv.c.o
[ 83%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/mutex-posix.c.o
[ 85%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/match.c.o
[ 87%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/pointer-pointer-map.c.o
[ 89%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/stringbuffer.c.o
[ 91%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/semaphore-posix.c.o
[ 93%] Building C object CMakeFiles/CDBUS_SHARED.dir/src/object-registry.c.o
Linking C shared library lib/libcdbus.so
[ 93%] Built target CDBUS_SHARED
Scanning dependencies of target CDBUS_MAIN_LOOP_EV_SHARED
[ 95%] Building C object CMakeFiles/CDBUS_MAIN_LOOP_EV_SHARED.dir/src/main-loop/main-loop-ev.c.o
Linking C shared library lib/libcdbus-ev.so
[ 95%] Built target CDBUS_MAIN_LOOP_EV_SHARED
Scanning dependencies of target CDBUS_MAIN_LOOP_GLIB_STATIC
[ 97%] Building C object CMakeFiles/CDBUS_MAIN_LOOP_GLIB_STATIC.dir/src/main-loop/main-loop-glib.c.o
Linking C static library lib/libcdbus-glib.a
[ 97%] Built target CDBUS_MAIN_LOOP_GLIB_STATIC
Scanning dependencies of target CDBUS_MAIN_LOOP_GLIB_SHARED
[100%] Building C object CMakeFiles/CDBUS_MAIN_LOOP_GLIB_SHARED.dir/src/main-loop/main-loop-glib.c.o
Linking C shared library lib/libcdbus-glib.so
[100%] Built target CDBUS_MAIN_LOOP_GLIB_SHARED
******end of log2**********

so after successful building i copied all libraries to my openwrt root file system. Then i tried to run one script which requires this l2bus_core.so library.its giving following error:
lua:symbol 'pthread_mutexatttr_destroy' : can't resolve symbol in lib /usr/lib/libcdbus.so.1
lua:error loading module "l2dbus_core" from file l2dbus_core.so

Can anybody help me to overcome this issue?

**Comment by tysenmoore-xse** [comment]
Are you by chance building CDbus with CDBUS_ENABLE_THREAD_SUPPORT enabled?  This option was originally intended to support a threaded version of CDbus.  However, we realized that the DBus reference library has too many issues with its thread implementation thus the CDbus threading option is typically not used--nor recommended, in fact it should probably be removed.  So if you build with this option off/undefined you should not have this dependency problem.  If you do however want to go down this path you'll need to modify the cmake [in CDbus] to link in the pthread library.

**Comment by sachin9900** [comment]
Thanks for your reply, i seen in code of cdbus but I am not getting how to disable thread support. Please help me in this.

**Comment by tysenmoore-xse** [comment]
Thread support in CDBus should be disabled by default.  Can you please make sure CDBUS_ENABLE_THREAD_SUPPORT is not enabled within your CDbus build?

**Comment by gschmottlach-xse** [comment]
By default (I believe) CDBUS  is *not* built with thread support. What I suspect is happening is that one of the main-loops you're linking the library with (libev or glib - likely glib)  may be requiring/expecting pthreads to be implicitly linked. You can do a "readelf -a <libname>" and then grep the output for "NEEDED" to see which shared library "needs" pthreads. You can build CDBUS using one or both of the main-loop implementations (e.g. either liibev and/or glib main-loops) and avoid the one pulling in pthreads. Also, you can also just as likely edit the CMakeLists.txt for CDBUS and tack on -lpthreads onto the core CBUS library to explicitly pull it in the library and satisfy the dependency. Make sure the generated pkgconfig reflects this dependency (which l2dbus will process).  If you go that route then just don't use CDBUS or L2DBUS from multiple threads - only a single thread should ever call it's API. This is usually the L2DBUS case since Lua doesn't explicitly support OS threads.

**Comment by tysenmoore-xse** [comment]
No further feedback
